### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by mbitson** [fireflight1/mcg#1]
Hey there!

There are a number of features that I believe this generator should include. Perhaps allowing the user to darken/lighten each shade per personal preference, and/or allowing direct export into the javascript code that is actually used to define a palette within the $mdThemingProvider. It'd also be cool if we could name our palette and/or completely swap out a color using a color picker. 

Obviously it would be ideal if the palettes could be saved on the site and recalled or searched by others for use on their material design projects- but this is much more work. It'd be even cooler if you could use the generator to generate an entire theme based on a series of palettes on the site. This is all much more work, but I think the first portion of this is at least feasible in my spare time.

I'm not requesting you develop all of these- but I am considering developing it myself. Would you be willing to work with me on improving this, or allow me to utilize your controller code thus far?

Thank you!
Cheers,
Mike

**Comment by fireflight1** [comment]
Sure, you can use the code and I'll be trying to help as much as I can.

**Comment by jagrodal** [comment]
Export to $mdThemingProvider palette format (JSON) would be amazing. 

Thanks

**Comment by mbitson** [comment]
Hey Jagrodal,

I'm working on getting the exact colors- bare with me while I do. In the meantime, this version supports a JSON export:
http://mcg.next-www.com/

I'll be adding multiple palettes with the option to export a set as a full theme in the standard $mdThemingProvider format.

Cheers!

EDIT: It now supports multiple palettes, a theme name, and exporting the angular code for a single palette or for an entire theme at once. In addition, it has controls for each individual color in the palette to override any color and two quick lighten/darken buttons to quickly modify a palette. More to come! (Ignore the code structure also, refactoring soon)
