### ISSUE TITLE
Show hexa for each generated color

### ISSUE THREAD

**Issue by danielgomezrico** [fireflight1/mcg#3]
I just see them visually but I need the hexa to use them.
![screen shot 2015-10-27 at 8 23 56 am](https://cloud.githubusercontent.com/assets/76348/10759220/1c7c62ae-7c84-11e5-9102-805f703330eb.png)

Will be cool to have that :+1:

**Comment by fireflight1** [comment]
There is an updated Version of the tool.  http://mcg.mbitson.com/#/

**Comment by danielgomezrico** [comment]
:+1:
